name: oak-wash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.2.0
  - numpy>=1.26.0
  - matplotlib>=3.8.0
  - folium>=0.15.0
  - scipy>=1.12.0
  - requests>=2.31.0
  - altair>=5.2.0
  - streamlit>=1.32.0
  - scikit-learn>=1.4.0
  - plotly>=5.18.0
  - jinja2>=3.1.0
  - branca>=0.6.0
  - h3-py>=4.2.0
  - geopandas>=0.14.0
  - pip
  - pip:
    - streamlit-folium>=0.15.0
    - fuzzywuzzy>=0.18.0
    - python-Levenshtein>=0.23.0 
    - kaleido>=0.2.1 